### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by dodoburner** [dodoburner/math-magicians#1]
I have setup the project using create-react-app and have created a development branch as per requirements of Gitflow. Kindly take a look if everything is done properly.

**Comment by dasileker** [comment]
### **Hi @dodoburner,** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## **Invalid Code Review Request**

You have submitted a project, that _**you should follow the Gitflow  and open a PR from feature branch to main as the requirements says, and also try to commit more**_

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by dodoburner** [comment]
@dasileker There is no pull request to be made since there is no feature branch? I only had to setup the project with create-react-app which automatically creates the main branch. What do you mean I should commit more there is nothing to commit
